// Generated by CoffeeScript 1.8.0
(function() {
  var Template, fs, string, sugar, templates,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  sugar = require('sugar');

  fs = require('fs');

  string = require('string');

  templates = {};

  Template = (function() {
    function Template(schema, section, obj) {
      this.schema = schema;
      this.section = section;
      this.obj = obj;
      this.attributes = {};
      this.create();
    }

    Template.prototype.getSection = function(key) {
      if (this.schema.sections[key]) {
        return this.schema.sections[key];
      }
    };

    Template.prototype.create = function() {
      var fields, key, _i, _len, _ref, _results;
      fields = this.getSection(this.section).fields;
      for (key in fields) {
        if (fields[key].required) {
          this.attributes[key] = fields[key]["default"] || '';
        }
      }
      if (this.validate()) {
        _ref = (Object.keys(fields)).intersect(Object.keys(this.obj));
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          _results.push(this.attributes[key] = this.obj[key]);
        }
        return _results;
      }
    };

    Template.prototype.validate = function() {
      var k, key, _i, _len, _ref;
      for (key in this.obj) {
        switch (typeof this.obj[key]) {
          case 'object':
            if (Array.isArray(this.obj[key])) {
              _ref = this.obj[key];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                k = _ref[_i];
                if (typeof this.obj[key][k] !== ('string' || 'number')) {
                  throw new Error('attribute array can\'t contain other objects or arrays');
                }
              }
            } else {
              throw new Error('object must be array');
            }
            break;
          case 'number':
          case 'string':
          case 'boolean':
            break;
          default:
            throw new Error('obj can contain attributes with number, string, boolean or plain array');
        }
      }
      return true;
    };

    Template.prototype.getAttributeFromSection = function(section, key) {
      return this.getSection(section).fields[key];
    };

    Template.prototype.set = function() {
      var args, k, key, _results;
      args = Array.prototype.slice.call(arguments, 0);
      if (typeof args[0] === 'object') {
        _results = [];
        for (key in args[0]) {
          switch (typeof args[0][key]) {
            case 'object':
              if (Array.isArray(args[0][key])) {
                _results.push((function() {
                  var _i, _len, _ref, _results1;
                  _ref = args[0][key];
                  _results1 = [];
                  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                    k = _ref[_i];
                    _results1.push(this.setOne(key, args[0][key][k]));
                  }
                  return _results1;
                }).call(this));
              } else {
                throw new Error('value must be array');
              }
              break;
            case 'string':
            case 'number':
            case 'boolean':
              _results.push(this.setOne(key, args[0][key]));
              break;
            default:
              console.log(typeof args[0][key], args[0][key], key);
              throw new Error('not available set object');
          }
        }
        return _results;
      } else if (args[1]) {
        return this.setOne(args[0], args[1]);
      } else {
        throw new Error('check set params');
      }
    };

    Template.prototype.setOne = function(key, value) {
      var attribute, current;
      attribute = this.getAttributeFromSection(this.section, key);
      if (attribute) {
        if (attribute.available) {
          if (__indexOf.call(attribute.available, value) >= 0) {
            return this.attributes[key] = value;
          } else {
            throw new Error('Not available value');
          }
        } else {
          if (attribute.multiple) {
            current = this.attributes[key];
            this.attributes[key] = [];
            if (current) {
              this.attributes[key].push(current);
            }
            return this.attributes[key].push(value);
          } else {
            return this.attributes[key] = value;
          }
        }
      } else {
        throw new Error('This key not in schema');
      }
    };

    Template.prototype.get = function(key) {
      return this.attributes[key];
    };

    Template.prototype.getAttributes = function() {
      return this.attributes;
    };

    Template.prototype.getName = function() {
      return this.get('name');
    };

    return Template;

  })();

  fs.readdirSync("" + __dirname + "/templates").forEach(function(file) {
    var name, schema;
    name = string(file).chompRight('.json').s;
    schema = require("./templates/" + file);
    return templates[name] = function(section, obj) {
      return new Template(schema, section, obj);
    };
  });

  module.exports = templates;

}).call(this);
